// Generates the secrets a local `npm run up` needs, once, into docker/.env.local.
//
// Anyone running this stack on their own machine gets their own Postgres password
// and JWT key here; nobody inherits the production ones. `.env` stays the file the
// VPS fills in for `npm run up:vps`, and compose reads this file AFTER it, so the
// values below win — for the local stack only.
//
// Written once and then left alone. Postgres applies POSTGRES_PASSWORD while it
// initialises an empty data volume and never again, so a password regenerated on
// every run would lock the api out of its own database on the second start.
import { randomBytes } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FILE = join(import.meta.dirname, '..', 'docker', '.env.local');

/** @returns {string} 32 random bytes, hex — the same shape as `openssl rand -hex 32` */
function secret() {
  return randomBytes(32).toString('hex');
}

/** @returns {boolean} whether compose's postgres volume already exists on this machine */
function pgVolumeExists() {
  try {
    execFileSync('docker', ['volume', 'inspect', 'tenderpilot_pgdata'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

// Silent when the file is already there: every local compose script calls this
// first, and a line per invocation would be noise.
if (!existsSync(FILE)) {
  const user = process.env.POSTGRES_USER ?? 'tenderpilot';
  const db = process.env.POSTGRES_DB ?? 'tenderpilot';
  const port = process.env.POSTGRES_HOST_PORT ?? '5433';
  const password = secret();

  writeFileSync(FILE, [
    '# GENERATED by scripts/localSecrets.mjs on the first `npm run up`. Gitignored.',
    '#',
    "# Secrets for THIS installation only. Production values live in the VPS's own",
    '# .env, which `npm run up:vps` reads instead — nothing here ever reaches it.',
    '#',
    '# Changing POSTGRES_PASSWORD here does NOT change it in an existing database:',
    '# Postgres keeps whatever the volume was created with. See the ALTER USER line',
    '# in the README.',
    `POSTGRES_PASSWORD=${password}`,
    '# The host-side URL, for psql and drizzle-kit against the published port.',
    `DATABASE_URL=postgres://${user}:${password}@localhost:${port}/${db}`,
    `JWT_SECRET=${secret()}`,
    '',
  ].join('\n'));

  console.log('Generated docker/.env.local (postgres password + JWT secret) for this machine.');

  // An existing volume keeps its old password, so the api would die on
  // `migrations failed (28P01)` with no hint as to why. Say it now, and point at
  // the fix that keeps the data rather than the one that deletes it.
  if (pgVolumeExists()) {
    console.warn([
      '',
      '  !  A tenderpilot_pgdata volume already exists, created with another password.',
      '     Postgres keeps the old one, so the api will fail with 28P01. Align the role',
      '     with the new value (the data is untouched) — take it from docker/.env.local:',
      '',
      '       docker exec tenderpilot-postgres-1 psql -U tenderpilot -d tenderpilot',
      "         -c \"ALTER USER tenderpilot WITH PASSWORD '<POSTGRES_PASSWORD>'\"",
      '',
    ].join('\n'));
  }
}
