import Link from "next/link";
import { ArrowUpRight, CalendarDays, Check, Building2 } from "lucide-react";
import { useCompany } from "@/hooks/useCompany";
import type { TenderListItem } from "@/lib/types";
import { dashboardSummary, shortDate } from "@/lib/utils/dashboardUtils";
import { CARD } from "@/lib/utils/workspaceStyleUtils";
import { cn } from "@/lib/utils/classNameUtils";
interface DashboardInsightsProps { tenders: TenderListItem[] }
export function DashboardInsights({ tenders }: DashboardInsightsProps) {
  const { counts, deadlines, total } = dashboardSummary(tenders);
  const company = useCompany();
  const stages = [{ label: "À analyser", count: counts.pending }, { label: "En analyse", count: counts.active }, { label: "Décision rendue", count: counts.go + counts["no-go"] }, { label: "À relancer", count: counts.failed }];
  return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-1">
    <section className={cn(CARD, "p-6")}><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Prochaines échéances</h2><CalendarDays size={17} className="text-muted" /></div><p className="mt-2 text-xs text-muted">Gardez une longueur d’avance.</p><div className="mt-5 space-y-4" data-testid="dashboard-deadlines">{deadlines.slice(0, 3).map((tender) => <Link href={`/tenders/${tender.id}`} key={tender.id} className="group flex items-center gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-warning-soft font-heading text-xl text-warning">{new Date(tender.deadline!).getDate()}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium group-hover:text-accent">{tender.reference}</p><p className="mt-1 text-xs text-muted">{shortDate(tender.deadline)}</p></div><ArrowUpRight size={15} className="text-muted" /></Link>)}{!deadlines.length && <p className="rounded-xl bg-background p-4 text-xs leading-6 text-muted">Aucune échéance à venir renseignée. Les dates extraites de vos dossiers apparaîtront ici.</p>}</div></section>
    <section className={cn(CARD, "p-6")}><h2 className="text-sm font-semibold">Parcours de vos dossiers</h2><p className="mt-2 text-xs text-muted">De l’import à la décision.</p><div className="mt-5 space-y-4">{stages.map((stage) => <div key={stage.label}><div className="mb-2 flex justify-between text-xs"><span className="text-muted">{stage.label}</span><span>{stage.count}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-soft"><div className="h-full rounded-full bg-accent transition-all duration-300" style={{ width: `${total ? stage.count / total * 100 : 0}%` }} /></div></div>)}</div></section>
    <section className="rounded-2xl border border-border bg-accent-soft p-6 md:col-span-2 xl:col-span-1"><Building2 size={22} strokeWidth={1.5} className="text-accent" /><h2 className="mt-4 font-heading text-xl">Une analyse qui vous ressemble.</h2>{company.isPending ? <div className="mt-3 h-12 animate-pulse rounded bg-soft" /> : company.isError ? <p role="alert" className="mt-3 text-xs text-warning">Profil indisponible. <button className="cursor-pointer underline" onClick={() => void company.refetch()}>Réessayer</button></p> : <p className="mt-3 text-xs leading-6 text-muted">{company.data.profile ? `${company.data.profile.raisonSociale} · ${company.data.references.length} références et ${company.data.team.length} profils pour appuyer vos réponses.` : "Ajoutez votre profil et vos références pour confronter chaque exigence à vos capacités réelles."}</p>}<Link href="/company" className="mt-4 flex items-center gap-2 text-xs font-semibold text-accent">{company.data?.profile ? <><Check size={14} /> Consulter mon entreprise</> : <>Compléter mon profil <ArrowUpRight size={14} /></>}</Link></section>
  </div>;
}
